# The dimensions of the CheapStat in millimeters.
# Mostly used for reference for now, but it would be cool
# if we could generate the CAD files from these declarations

[cheapstat]
width     = 57.35
height    = 96.58
depth     = 20.00 # estimated, should probably measure this out
thickness =  1.60

[cheapstat.top] # the section with the LCD
height = 32.60

[cheapstat.top.cutout]
height = 6.91
width  = 6.91 # FIXME: verify this


[cheapstat.bottom] # the section with all the connections
height = 51.00

[cheapstat.bottom.cutout]
height = 5.52
width  = 7.17
